# Generated by Django 5.2.6 on 2025-10-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Match'), ('MATCHED', 'Matched with Buddy'), ('COMPLETED', 'Walk Completed'), ('CANCELLED', 'Request Cancelled')], default='PENDING', max_length=10),
        ),
    ]
